t1_contact/urls.py
from django.conf.urls import patterns, include, url

from .views import HomePersonListView


urlpatterns = patterns(
    '',
   url(r'^$', HomePersonListView.as_view(), name="person-detail"),
   )

t3_httprequests/urls.py
from django.conf.urls import patterns, include, url

from .views import HttpRequestListView


urlpatterns = patterns(
    '',
   url(r'^$', HttpRequestListView.as_view()),

   )

test42cc/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import UpdateView

from django.http import HttpResponsePermanentRedirect

from django.conf import settings

from t5_editform.views import CustomProfileUpdateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^$',
     lambda request: HttpResponsePermanentRedirect('/1')),
    url(r'^(?P<pk>\d+)/$', include('t1_contact.urls')),
    url(r'^requests/$', include('t3_httprequests.urls')),
    url(r'^update/(?P<pk>\d+)/$',  CustomProfileUpdateView.as_view(), name="update"),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT, }),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
    
)

t1_contact/models.py
from django.db import models

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver


class CustomProfile(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    birth_date = models.DateField(verbose_name="Date of birth")
    bio = models.TextField()
    email = models.EmailField()
    jabber = models.EmailField()
    skype = models.CharField(max_length=30)
    other_contacts = models.TextField()
    photo = models.ImageField(upload_to="photo", blank=True)

    def __unicode__(self):
        return self.first_name


class Update(models.Model):

    TYPE_CHOICES = (
            ('C', 'create'),
            ('U', 'update'),
            ('D', 'delete'),
            )
    update_type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    model_name = models.CharField(max_length=30)
    time = models.DateTimeField(auto_now_add=True)


@receiver(post_save)
def update_callback(sender, **kwargs):
    model_name = sender._meta.object_name
    if model_name == 'Update':
        return
    update_type = 'C' if kwargs.get('created', False) else 'U'
    u = Update(update_type=update_type, model_name=model_name)
    u.save()


@receiver(post_delete)
def delete_callback(sender, **kwargs):
    model_name = sender._meta.object_name
    if model_name == 'Update':
        return
    update_type = 'D'
    u = Update(update_type=update_type, model_name=model_name)
    u.save()

t3_httprequests/models.py
from django.db import models


class HttpRequestLog(models.Model):
    date = models.DateTimeField('Request date/time', db_index=True)
    request_method = models.CharField('Method', max_length=6, db_index=True)
    path = models.CharField(max_length=256)
    query_string = models.CharField(max_length=256)
    priority = models.IntegerField(default=1)

    #http_user_agent = models.CharField(max_length=128)
    #http_referer = models.CharField(max_length=256)
    #remote_addr = models.CharField(max_length=15) #127.000.000.001

    def __unicode__(self):
        return self.path

t9_countobjects/models.py
from django.db import models

# Create your models here.

t1_contact/views.py
from django.views.generic import DetailView

from .models import CustomProfile


class HomePersonListView(DetailView):
    model = CustomProfile
    queryset = CustomProfile.objects.order_by('-first_name').all()
    template_name = "test42cc/index.html"
    context_object_name = "CustomProfile"


    def get_context_data(self, **kwargs):
        context = super(HomePersonListView, self).get_context_data(**kwargs)
        context['pk'] = CustomProfile.objects.get(pk=1)
        return context

t3_httprequests/views.py
from django.views.generic import ListView

from .models import HttpRequestLog


class HttpRequestListView(ListView):
    model = HttpRequestLog
    queryset = model.objects.all().order_by('-date')[:10]
    template_name = "t3_httprequests/httprequestlogentry_list.html"
    context_object_name = "http"

t5_editform/views.py
import json
from django.http import HttpResponse
from django.views.generic import UpdateView
from braces.views import LoginRequiredMixin, CsrfExemptMixin

from t1_contact.models import CustomProfile
from t5_editform.form import EditForm


class CustomProfileUpdateView(LoginRequiredMixin, CsrfExemptMixin, UpdateView):
    """
    You must login to see template edit_person

    """
    model = CustomProfile
    form = EditForm
    template_name = "t5_editform/editform.html"
    success_url = '.'
    
    def form_valid(self, form):
        """
        If the request is ajax, save the form and return a json response.
        Otherwise return super as expected.
        """
        if self.request.is_ajax():
            self.object = form.save()
            return HttpResponse(json.dumps("success"),
                mimetype="application/json")
        return super(CustomProfileUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        """
        We haz errors in the form. If ajax, return them as json.
        Otherwise, proceed as normal.
        """
        if self.request.is_ajax():
            return HttpResponseBadRequest(json.dumps(form.errors),
                mimetype="application/json")
        return super(CustomProfileUpdateView, self).form_invalid(form)

t9_countobjects/views.py
# Create your views here.

templates/base.html
{% load auth_user_extra %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ BASE_TEMPLATE_TITLE }} | {% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">

      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }



      /* Custom page CSS
      -------------------------------------------------- */
      /* Not required for template or sticky footer method. */

      .container {
        width: auto;
        max-width: 680px;
      }
      .container .credit {
        margin: 20px 0;
      }

    </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/static/css/bootstrap-sortable.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">

    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>   
    <script src="http://malsup.github.com/jquery.form.js"></script>

    <script src="/static/js/bootstrap-sortable.js"></script> 

    <script type="text/javascript">
        $(document).ready(function() {

            $( "#id_birth_date" ).datepicker();

            $('#ajax_form').ajaxForm({
              target:        '#ajax_form',
              beforeSubmit:  showRequest,
              success:       showResponse 
            }); 
            function showRequest(formData, jqForm, options) { 
                var queryString = $.param(formData);
             
                alert('After update you can see changes in model.');
                return true; 
            } 

            function showResponse(responseText, statusText, xhr, $form)  {
                
                document.write('<img src="/static/img/ajax-loader.gif" class="img-rounded" style="margin-left: 33%"/>')
                 
                document.write('<p style="margin-right: 20%">Lodaing...</p>')
                window.setTimeout("location=('/1');",3000);
            } 
            
        }); 

    </script>
</head>

<body>
  <div class="container pull-right">
    <br />
  {% if user.is_authenticated %}
  {% edit_link user %}
  <a href="{% url 'auth_logout' %}" class="pull-right" style="margin-right: 10px; margin-left: 10px">Logout</a>
  <a href="{% url 'update' user.id %}" class="pull-right">Edit</a>
  {% else %}
  <a href="{% url 'auth_login' %}" class="pull-right" style="margin-right: 10px; margin-left: 10px">Log in</a>
  
  {% endif %}
  </div>

{% block content %}{% endblock content %}


    <script src="/static/js/bootstrap.min.js"></script>


</body>
</html>

templates/edit_object_link.html
<a href="{{ url }}" id="admin_link" class="pull-right">(admin)</a>

templates/t3_httprequests/httprequestlogentry_list.html
{% extends "base.html" %}

{% block title %}Requests page.{% endblock title %}

{% block content %}

    <h3>42 Coffee Cups Test Assignment</h3>
<table class="table sortable">
  <thead>
   <tr>
     <th>Date</th>
     <th>Method</th>
     <th>Path</th>
     <th>Priority</th>
   </tr>
  </thead>
{% for e in http %}
  <tbody>
   <tr>
     <td>{{ e.date }}</td>
     <td>{{ e.request_method }}</td>
     <td>{{ e.path }}</td>
     <td>{{ e.priority }}</td>
   </tr>
  </tbody>
{% endfor %}
</table>
<a href="/">Home</a>
{% endblock content %}

templates/t5_editform/editform.html
{% extends "base.html" %}
{% block title %}42 Coffee Cups Test Assignment: Edit{% endblock title %}


{% block content %}
    <div class="span1"></div>
    <div class="span11">

    <form id="ajax_form" enctype="multipart/form-data" method="post" action=".">{% csrf_token %}
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span4">
                    <label>First Name:</label>
                    {{ form.first_name }}
                    <label>Last Name:</label>
                    {{ form.last_name }}
                    <label>Birth date:</label>
                     {{ form.birth_date }}<br />
                    {% if form.instance.photo %}
                    <label>Photo:</label>
                    <img src="{{ form.instance.photo.url }}" class="img-rounded" style="margin-top: 10px;"/>
                    {{ form.photo }}
                    
                    
                    {% else %}
                        <label>Photo:</label>
                        {{ form.photo }}
                    {% endif %}
                </div>
                <div class="span4">
                    <p>Contacts:</p>
                    <label>Email:</label>
                     {{ form.email  }}
                    <label>Jabber:</label>
                    {{ form.jabber }}
                    <label>Skype:</label>
                    {{ form.skype }}
                    <label>Other Contacts:</label>
                    {{ form.other_contacts }}
                    <label>Bio:</label>
                    {{ form.bio }}
                </div>
            </div>

            <!-- submit block -->
            <div class="row" style="margin-top: 20px;">
                <div class="span1">
                    <input class="btn" type="submit" value="Send" id="refresh">
                </div>
                    <div id="loading-status" ></div>
                <div class="span1">
                    <a href="/1">Cancel</a>
                </div>

        <hr />
            </div>

        </div>

    </div>


{% endblock content %}

templates/test42cc/index.html
{% extends "base.html" %}

{% block title %}Index page.{% endblock title %}

{% block content %}

    <h3>42 Coffee Cups Test Assignment</h3>



    {% if CustomProfile %}
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span4">
                    <p><small><b>Name</b></small>: {{ CustomProfile.first_name }}</p>
                    <p><small><b>Last Name</b></small>: {{ CustomProfile.last_name }}</p>
                    <p><small><b>Date of birth</b></small>: {{ CustomProfile.birth_date }}</p>
                    <p style="max-width: 250px;"><small><b>Photo:</b></small></p>
                    {% if CustomProfile.photo %}
                    <img src="/media/{{ CustomProfile.photo }}" class="img-rounded" />
                    {% else %}
                    <div class="alert alert-error">
                        <h3>Error: no photo found.</h3>
                    </div>
                        
                    {% endif %}
                </div>
                <div class="span4">
                    <p>Contacts:</p>
                        <p><small><b>Email:</b></small> {{ CustomProfile.email}}</p>
                        <p><small><b>Jabber:</b></small> {{ CustomProfile.jabber }}</p>
                        <p><small><b>Skype:</b></small> {{ CustomProfile.skype }}</p>
                        <p><small><b>Other Contacts:</b></small>
                            {{ CustomProfile.other_contacts }}</p>
                    <p style="max-width: 250px;"><small><b>Bio:</b></small>
                    {{ CustomProfile.bio }}</p>
                </div>
            </div>
        </div>
        
            
        
        <hr />
        <div class="container-fluid">
            <a href="/requests/">requests</a>
        </div>
    {% endif %}
{% endblock content %}